FROM mambaorg/micromamba:2-debian12

USER root

WORKDIR /working

COPY env_rasters.yml .
RUN micromamba install -f env_rasters.yml -y && \
    micromamba clean --all --yes

COPY rasters.py .

ARG BBOX
ARG API

ENV BBOX=$BBOX
ENV API=$API

CMD ["python", "rasters.py"]