FROM mambaorg/micromamba:2-debian12

WORKDIR /working

COPY ./environments/env_rasters.yml .
RUN micromamba install -f env_rasters.yml -y && \
    micromamba clean --all --yes

COPY ./scripts/download_rasters.py .

USER root

CMD ["python", "download_rasters.py", "--api=nrcan", "--bbox=-52.695408,47.570156,-52.681074,47.575426"]